// <auto-generated />
using MVCApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCApp.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260203175450_CreateVillaAndVillaNumberAndSeedTable")]
    partial class CreateVillaAndVillaNumberAndSeedTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVCApp.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Casagrand",
                            Price = 300.0
                        },
                        new
                        {
                            Id = 2,
                            Name = "RainbowVistas",
                            Price = 200.0
                        },
                        new
                        {
                            Id = 3,
                            Name = "MarinaSkies",
                            Price = 400.0
                        });
                });

            modelBuilder.Entity("MVCApp.Models.VillaAmenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VillaId");

                    b.ToTable("villaAmenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pool",
                            VillaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Gameboy",
                            VillaId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Gym",
                            VillaId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "PlayCourt",
                            VillaId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "Security",
                            VillaId = 3
                        },
                        new
                        {
                            Id = 6,
                            Name = "Shop",
                            VillaId = 3
                        },
                        new
                        {
                            Id = 7,
                            Name = "Jacuzzi",
                            VillaId = 3
                        });
                });

            modelBuilder.Entity("MVCApp.Models.VillaAmenity", b =>
                {
                    b.HasOne("MVCApp.Models.Villa", "Villa")
                        .WithMany("VillaAmenity")
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });

            modelBuilder.Entity("MVCApp.Models.Villa", b =>
                {
                    b.Navigation("VillaAmenity");
                });
#pragma warning restore 612, 618
        }
    }
}
